- name: task level varibales
  hosts: local
  connection: local
  vars:
    name: mittu
    location: newcastle
  tasks:
  - name: personal details
    vars:
      course: ansible # task level variables it gives priority to task level
      duration: 10
    ansible.builtin.debug:
      msg: "hello {{ course }} course {{ duration }}"